# Generated by Django 4.2 on 2023-08-02 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vulnet_app', '0013_connection_connectionvulnerability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='first_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstdevice', to='vulnet_app.device'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='second_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seconddevice', to='vulnet_app.device'),
        ),
    ]
